### ISSUE TITLE
uuid abruf gibt HTTP ERROR 400 zuürck

### ISSUE THREAD

**Issue by flex-0** [philipp2310/snips-bring-shopping#12]
Hallo,
bevor ich mich zum Horst mache, ich hab nicht wirklich (eigentlich gar keine) Ahnung, wie Snips funktioniert.

Jedenfalls, bei dem Versuch die UUID über die api abzurufen erhalte ich immer einen 400 zurück.
Funktioniert das nicht mehr oder darf ich das nicht über den Browser abrufen?

**Comment by philipp2310** [comment]
Hallo flex,

doch, das muss über den Browser passieren und hat erstmal nichts mit Snips zu tun. Ich habe es gerade nochmal getestet, bei mir klappt es. Folgender Link sollte dir zumindest erstmal ein E-Mail/Passwort Kombination nicht vorhanden bringen:
[https://api.getbring.com/rest/bringlists?email=XXXwilmaflintstone.ai@gmail.com&password=XXX](https://api.getbring.com/rest/bringlists?email=XXXwilmaflintstone.ai@gmail.com&password=XXX)

Leider habe ich egal mit welchen Sonderzeichen ich es aufrufe und wie ich denk Link verunstalte, es nicht geschafft den Fehler zu reproduzieren.
Bekommst du bei meinem Link erstmal die Passwort Meldung?

**Comment by flex-0** [comment]
Hallo phillip,

ja das klappt. Ich habe es mit mehreren Browsern versucht, Antivirenscann deaktiviert, aber bei allen Versuchen erhalte ich den 400er Error.

**Comment by philipp2310** [comment]
Wenn mein Link funktioniert, dann muss es eigentlich an deinen Daten liegen. Sind da irgendwelche "verdächtigen" Sonderzeichen enthalten? Alle die mir eingefallen sind hatten leider andere Auswirkungen als den 400er Fehler.
Wenns gar nicht klappt kann ich höchstens anbieten, dass ich mit deinen Daten mal schaue (dann aber besser nicht hier öffentlich ;))

**Comment by flex-0** [comment]
Hallo phillip,

du hattest recht, es lag wohl an meinem Passwort   :\c)7>)i+Mu-ZPG[53.z
Muss wohl zu viele Sonderzeichen enthalten oder welche mit denen es Probleme gibt. Das einloggen auf der Webapp und in der Android app hat allerdings immer funktioniert. 

Nach dem ich mir jetzt über <Passwort vergessen> ein neues Passwort von Bring habe zusenden lassen funktioniert es einwandfrei.

Das werde ich allerdings gleich im Anschluss wieder ändern, da es sehr kurz ist und nur aus Kleinbuchstaben besteht.

Besten Dank für deine Hilfe und ein schönes Wochende!

**Comment by philipp2310** [comment]
Klasse dass es funktioniert hat!

Dir auch ein schönes Wochenende und viel Spaß mit Snips!
